name: housekeep

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited # for base branch change
      - synchronize # for new commits

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
        with:
          fail_on_error: true

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: shellcheck
        uses: reviewdog/action-shellcheck@5ebd09ddbe2ebb471646ce234c6c8dd18663ca7c # v1.30.0
        with:
          fail_on_error: true

  trigger:
    uses: ./.github/workflows/milestone-setter.yaml
    permissions:
      contents: write # for creating milestone
      pull-requests: write
    with:
      branch_name_filter: "(feature|release)/.*"
      milestone_prefix: 'prefix-'
      milestone_suffix: '-suffix'
